### ISSUE TITLE
Milestone 2 feedback

### ISSUE THREAD

**Issue by lmguzman** [UBC-MDS/554_Survey#14]
Fantastic job with this submission. The survey was very clear and your EDA covered all the important graphs.

This feedback is not necessarily for something you need to improve in this milestone, since you have done a very good job, but its ideally to get you thinking about the analysis of your data.

Since you found that you have a big unbalance in the number of people that did do a masters degree vs people who only did bachelors, I was wondering if you could a cohort type of strategy, where you keep the control:treatment ratio the same. Or you did a matching controls scenario to maximize what you can do with the 10 people who did their masters.

**Comment by lyiris22** [comment]
Thank you for the feedback! We would try to do balancing in the analysis.
