### ISSUE TITLE
Feedback for milestone 1

### ISSUE THREAD

**Issue by lmguzman** [UBC-MDS/554_Survey#8]
Great job in milestone 1.

Some things you might consider for your survey:

- I see that many of your confounding variables relate to the subject of bachelor's degree that your participants did. Have you thought about how will you set up this question? Will you have a multiple choice question? or a separate question for each of the subjects?

- I think it would be useful to have another question regarding job experience in general and a more specific question about job experience relevant to the program. 

- Given that you will have max 60 participants, I don't think you can separate your data into training and testing. Another point related to this, is that all you need to do is a regression model, you do not need to test your model using testing data, and there are other ways you can select the model of best fit. Remember that you are trying to infer causality, not necessarily build a predictive model.

**Comment by rzitomer** [comment]
Thanks for the feedback. Below are our responses:
- We decided to have a multiple choice question and include an options for students who have none of the listed backgrounds.
- Makes sense, we've updated the question about job experience to let participants put the degree to which their job experience is or isn't related to the program.
- Got it, we won't make separate training and testing data when we analyze the data and will build a regression model.
